### ISSUE TITLE
Weird crash (Biome Decorator?)

### ISSUE THREAD

**Issue by Eufranio** [Benimatic/twilightforest#53]
When a player of my server went to Twilight Forest, the whole server crashed.

Crash: http://pastebin.com/argTuhYq

**Comment by keybounce** [comment]
Aha. Looking at the crash portion, I was thinking "incompatible forge version".

Looking later down, I saw this:
 An unsupported base software is installed: 'thermos, cauldron, craftbukkit, mcpc, kcauldron'. This is NOT supported.

Sorry -- Cauldron is NOT fully compatible with forge.
Especially anything with a core mod / ASM replacement.

**Comment by Eufranio** [comment]
Never had issues with something like it. Well, i can't use Twilight Forest in my server by a while so i'm closing the issue.

**Comment by Bogdan-G** [comment]
Strange, Thermos issues?

**Comment by Eufranio** [comment]
No, this issue was fixed a time ago. The devs simply dont care to the problem if there is Thermos >.>

**Comment by ensirius** [comment]
Thermos used client method to display world name at crash. The real issue is that twilightforest decorator takes more than 10s. Here commit that fixed that https://git.io/vdghl. My server suffers every day 2-3 times. I am using 2.3.8.dev build.

**Comment by Bogdan-G** [comment]
>Here commit that fixed problem in Thermos https://git.io/vdghl

there is information that this did not solve the problem, can only part.
